---
- name: Install packages
  ansible.builtin.package:
    state: present
    name:
      - nano
      - unzip
  become: true

- name: Check if install.sh exists
  ansible.builtin.stat:
    path: ~/.nano/install.sh
  register: _install_sh

- name: Download and install Improved Nano Syntax Highlighting Files
  when: not _install_sh.stat.exists
  block:
    - name: Create tmp dir
      ansible.builtin.tempfile:
        state: directory
      register: _tmp_nanorc

    - name: Download install.sh
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/scopatz/nanorc/master/install.sh
        dest: "{{ _tmp_nanorc.path }}/install.sh"
        mode: 0755

    - name: Install Improved Nano Syntax Highlighting Files
      ansible.builtin.command: "{{ _tmp_nanorc.path }}/install.sh"
      args:
        creates: ~/.nano/install.sh

    - name: Remove temp dir
      ansible.builtin.file:
        path: "{{ _tmp_nanorc.path }}"
        state: absent
      when: _tmp_nanorc.path is defined

- name: Configure nano
  ansible.builtin.blockinfile:
    path: ~/.nanorc
    block: |
      set tabsize 4
      set tabstospaces
    state: present
